# @package _global_
model:
  model_name: 'guidenet'
  model_params:
    depth_scale: 80
    enc_channels: 512

loss:
  loss_name: 'masked_mse'
  loss_params:
    params: null

optimizer:
  opt_name: 'Adam'  # Should be a torch.optim class name
  opt_params:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0.0

scheduler:
  scheduler_name: 'MultiStepLR'
  scheduler_params:
    milestones: [20,40,60]
    gamma: 0.5