# @package _global_
model:
  model_name: 'sparse_to_dense'
  model_params:
    depth_scale: 80

loss:
  loss_name: 'self_sup_sparse_to_dense_loss'
  loss_params:
    gamma: [0.1, 0.1]

optimizer:
  opt_name: 'Adam'  # Should be a torch.optim class name
  opt_params:
    lr: 0.00001
    betas: [0.9, 0.999]
    weight_decay: 0.0

scheduler:
  scheduler_name: 'StepLR'
  scheduler_params:
    step_size: 5
    gamma: 0.5

dataset:
  use_rgb: true
  use_grayscale: true
  use_rgb_near: true
  use_intrinsics: true
  use_pose: true  # pose estimation
  horizontal_flip: false
